name: weakvtg
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - argh=0.26.2=pyh9f0ad1d_1002
  - attrs=20.2.0=py_0
  - blas=1.0=mkl
  - brotlipy=0.7.0=py38h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2020.10.14=0
  - catalogue=2.0.4=py38h578d9bd_0
  - certifi=2020.6.20=py38_0
  - cffi=1.14.6=py38h400218f_0
  - chardet=4.0.0=py38h06a4308_1003
  - click=7.1.2=pyh9f0ad1d_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - configparser=5.0.2=pyhd8ed1ab_0
  - cpuonly=1.0=0
  - cryptography=3.4.7=py38hd23ed53_0
  - cymem=2.0.5=py38h709712a_2
  - cython-blis=0.7.4=py38h5c078b8_0
  - dataclasses=0.8=pyhc8e2a94_1
  - docker-pycreds=0.4.0=py_0
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.10.4=h5ab3b9f_0
  - gitdb=4.0.7=pyhd8ed1ab_0
  - gitpython=3.1.18=pyhd8ed1ab_0
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - gql=0.1.0=py_0
  - graphql-core=3.1.5=pyhd8ed1ab_0
  - idna=2.10=pyhd3eb1b0_0
  - iniconfig=1.1.1=py_0
  - intel-openmp=2021.3.0=h06a4308_3350
  - jinja2=3.0.1=pyhd8ed1ab_0
  - jpeg=9b=h024ee3a_2
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libiconv=1.15=h63c8f33_5
  - libidn2=2.3.2=h7f8727e_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.17.2=h780b84a_1
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h85742a9_0
  - libunistring=0.9.10=h27cfd23_0
  - libuv=1.40.0=h7b6447c_0
  - libwebp-base=1.2.0=h27cfd23_0
  - lz4-c=1.9.3=h295c915_1
  - markupsafe=2.0.1=py38h497a2fe_0
  - mkl=2021.3.0=h06a4308_520
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.0=py38h42c9631_2
  - mkl_random=1.2.2=py38h51133e4_0
  - more-itertools=8.5.0=py_0
  - murmurhash=1.0.5=py38h709712a_0
  - ncurses=6.2=he6710b0_1
  - nettle=3.7.3=hbbd107a_1
  - ninja=1.10.2=hff7bd54_1
  - numpy=1.20.3=py38hf144106_0
  - numpy-base=1.20.3=py38h74d4b33_0
  - nvidia-ml=7.352.0=py_0
  - olefile=0.46=py_0
  - openh264=2.1.0=hd408876_0
  - openjpeg=2.3.0=h05c96fa_1
  - openssl=1.1.1k=h7f98852_0
  - packaging=20.4=py_0
  - pathtools=0.1.2=py_1
  - pathy=0.6.0=pyhd8ed1ab_0
  - pillow=8.3.1=py38h2c7a002_0
  - pip=20.2.4=py38_0
  - pluggy=0.13.1=py38_0
  - preshed=3.0.5=py38h709712a_1
  - promise=2.3=py38h578d9bd_3
  - protobuf=3.17.2=py38h709712a_0
  - psutil=5.8.0=py38h497a2fe_1
  - py=1.9.0=py_0
  - pycparser=2.20=py_2
  - pydantic=1.8.2=py38h497a2fe_0
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pyparsing=2.4.7=py_0
  - pysocks=1.7.1=py38h06a4308_0
  - pytest=6.1.1=py38_0
  - python=3.8.11=h12debd9_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pytorch=1.9.0=py3.8_cpu_0
  - pyyaml=5.4.1=py38h497a2fe_0
  - readline=8.1=h27cfd23_0
  - requests=2.25.1=pyhd3eb1b0_0
  - sentry-sdk=1.3.1=pyhd8ed1ab_0
  - setuptools=52.0.0=py38h06a4308_0
  - shellingham=1.4.0=pyh44b312d_0
  - shortuuid=1.0.1=py38h578d9bd_4
  - six=1.16.0=pyhd3eb1b0_0
  - smart_open=5.1.0=pyhd8ed1ab_1
  - smmap=3.0.5=pyh44b312d_0
  - spacy=3.1.1=py38hfc89cab_0
  - spacy-legacy=3.0.8=pyhd8ed1ab_0
  - sqlite=3.36.0=hc218d9a_0
  - srsly=2.4.1=py38h709712a_0
  - subprocess32=3.5.4=py_1
  - thinc=8.0.8=py38hfc89cab_0
  - tk=8.6.10=hbc83047_0
  - toml=0.10.1=py_0
  - torchaudio=0.9.0=py38
  - torchtext=0.10.0=py38
  - torchvision=0.10.0=py38_cpu
  - tqdm=4.62.0=pyhd8ed1ab_0
  - typer=0.3.2=pyhd8ed1ab_0
  - typing-extensions=3.10.0.0=hd3eb1b0_0
  - typing_extensions=3.10.0.0=pyh06a4308_0
  - urllib3=1.26.6=pyhd3eb1b0_1
  - wandb=0.11.2=pyhd8ed1ab_0
  - wasabi=0.8.2=pyh44b312d_0
  - watchdog=0.10.4=py38h578d9bd_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h516909a_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
  - pip:
    - en-core-web-sm==3.1.0
